# Generated by Django 5.2.1 on 2026-03-13 02:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0007_cashdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='meta_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='purpose',
            field=models.CharField(choices=[('wallet_topup', 'Wallet Top Up'), ('order_payment', 'Order Payment')], default='wallet_topup', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
