# Generated by Django 5.2.1 on 2026-05-06 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0009_adminsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealticket',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('scanned', 'Scanned'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CollectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=16)),
                ('service_date', models.DateField(db_index=True)),
                ('meal_name', models.CharField(max_length=120)),
                ('meal_type', models.CharField(max_length=80)),
                ('quantity', models.IntegerField(default=1)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_notes', models.CharField(blank=True, default='', max_length=255)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='canteen.order')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_collection_orders', to=settings.AUTH_USER_MODEL)),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_collection_orders', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_orders', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='canteen.mealticket')),
            ],
            options={
                'ordering': ('-scanned_at',),
                'unique_together': {('service_date', 'order_number')},
            },
        ),
    ]
